services:
  rstudio-pos-devcontainer:    
    env_file:
      - .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        ENABLE_SWITCH_USER: "true"
        USERNAME: rstudio
    image: rstudio-pos-devcontainer:latest
    container_name: rstudio-pos-devcontainer  # docker exec -it rstudio-devcontaier bash
    environment:
      PASSWORD: "toor"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      SPARK_MASTER: spark://spark-master:7077      
      XAUTHORITY: /tmp/.mutter-Xwaylandauth-devc
    ports:
      - "8787:8787" # http://localhost:8787/ user: rstudio password: toor
      - "8888:8888" # http://localhost:8888/
    volumes:
      - ..:/workspace:rw      
      - ../src:/home/rstudio/src/r:rw
      - ../projects/sem2-ciclo-de-vida-e-linguagem-r/TEMA 3/workspace:/home/rstudio/workspace:rw./.a        
      - vscode-extensions-shared:/home/rstudio/.vscode-server/extensions:rw
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8787/ >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

    networks:
      - rs-network    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  vscode-extensions-shared:    
    external: true
networks:
  rs-network:
    external: true

